### ISSUE TITLE
The `fun.y` argument of `stat_summary()` is deprecated as of ggplot2 3.3.0.

### ISSUE THREAD

**Issue by Henrique-reolon** [csbl-usp/CEMiTool#100]
Warning:
The `fun.y` argument of `stat_summary()` is deprecated as of ggplot2 3.3.0.
ℹ Please use the `fun` argument instead.
ℹ The deprecated feature was likely used in the CEMiTool package.
  Please report the issue to the authors.
---
Backtrace:
    ▆
 1. └─CEMiTool::cemitool(...)
 2.   ├─CEMiTool::plot_profile(...)
 3.   └─CEMiTool::plot_profile(...)
 4.     └─CEMiTool (local) .local(cem, ...)
 5.       └─base::lapply(...)
 6.         └─CEMiTool (local) FUN(X[[i]], ...)
 7.           └─ggplot2::stat_summary(...)
 8.             └─ggplot2:::deprecate_warn0("3.3.0", "stat_summary(fun.y)", "stat_summary(fun)")

**Comment by pedrostrusso** [comment]
Hi @Henrique-reolon thanks, I just updated the package, should be fixed in Bioconductor starting tomorrow.

**Comment by Henrique-reolon** [comment]
thank you very much!
