### ISSUE TITLE
Interaction networck: Unlabeled data points (too many overlaps) 

### ISSUE THREAD

**Issue by Henrique-reolon** [csbl-usp/CEMiTool#101]
Olá @pedrostrusso !
Primeiramente gostaria de agradecer pelo desenvolvimento desta excelente ferramenta, bem como pela presteza em responder minha última solicitação.
Agora estou enfrentando um novo problema com relação a rede de interação:
- Ao rodar o comando:  generate_report(cem, directory="./Report"), tenho recebido a seguinte mensagem de erro: 
1: ggrepel: 14 unlabeled data points (too many overlaps). Consider increasing max.overlaps.
Poderia me ajudar a resolver tal questão?
Desde já agradeço pela atenção!

![M1](https://github.com/csbl-usp/CEMiTool/assets/163589850/321df5d5-0586-4c61-b04b-ca298e5a7d1a)
![M3](https://github.com/csbl-usp/CEMiTool/assets/163589850/d21b84bc-cefb-4724-8dd6-876c6f9d0ac1)

**Comment by pedrostrusso** [comment]
Oi @Henrique-reolon, experimente rodar o seguinte comando: `options(ggrepel.max.overlaps = Inf)`. Pelo que eu entendi o problema é que como os módulos  são muito grandes, o ggrepel (o pacote que usamos pra fazer as anotações dos genes) acha que tem coisa demais pra anotar e/ou que as anotações acabam se sobrepondo. Note que com o comando que citei esse cuidado do pacote de não sobrepor as anotações pode acabar sendo sobreescrito.

**Comment by Henrique-reolon** [comment]
Obrigado @pedrostrusso, problema resolvido!
