### ISSUE TITLE
Bioconductor Submission

### ISSUE THREAD

**Issue by lecardozo** [csbl-usp/CEMiTool#16]
Alright guys ( @matheuscburger and @pedrostrusso  ), the time to submit CEMiTool to Bioconductor has come.
#### These are the requirements that need to be satisfied in order to submit the package:

- :warning: : _Pass **R CMD build**, **R CMD check**, and **R CMD BiocCheck** (see the R CMD check cheatsheet and the BiocCheck package) on all supported platforms (Windows, Macintosh, Linux) with no errors or warnings, using an appropiate version of R. To work out which version that is, see useDevel._

- :warning: _The result of **R CMD build** must be **less than 4MB**_ 
  ~~Our build is **>50MB**, because of the report files. We need to discuss this. :eyes:~~
  Our build is **>8MB**, because of external data. Thanks for correcting me, @matheuscburger !

- :warning: _**R CMD check** must complete within **5 minutes**._
  There are some warnings and some errors in the check step. We need to take a look at it as well. :eyes:

- _:warning: Contain a DESCRIPTION file with valid contact information, an informative title and description, correct license specification, **appropriate biocViews terms**, valid version number._

- _:warning: **Set Version: 0.99.0 in the DESCRIPTION**. Subsequent versions created during the review process will be numbered 0.99.1, 0.99.2, etc. When released, your package’s version number will be automatically incremented to 1.0.0._

- _:white_check_mark: Contain a NAMESPACE that imports all symbols used in the package, and exports just those symbols the package author identifies as appropriate. Use of a NAMESPACE implies that appropriate packages are mentioned in the Imports: field of the DESCRIPTION file._

- _:white_check_mark: Contain a vignette that illustrates the major uses of the package. The vignette must be evaluated during package installation; a static vignette is not acceptable._

- _:white_check_mark: Contain comprehensive help pages. This includes accurate description of function parameter and return values, and meaningful examples._

- _:warning: Make use of appropriate existing packages (e.g., biomaRt, AnnotationDbi, Biostrings) and classes (e.g., **ExpressionSet**, AnnotatedDataFrame, RangedData, Rle, DNAStringSet) to avoid duplication of functionality available in other Bioconductor packages._

- _:white_check_mark: Contain no extraneous files (e.g., ‘.DS_Store’, ‘.project’, ‘.svn’, etc.), files with invalid names (e.g., differing only in case), or code that cannot be distributed under the license specified by the author._

- _:white_check_mark: Packages should have a descriptive name that is not already in use. See if it is by running biocLite("myPackageName"). You cannot have a package name that is case-insensitively equal to an existing package name in CRAN or Bioconductor._

**Comment by pedrostrusso** [comment]
BiocCheck was run again, no more errors! Just a few reccomendations and considerations:
$recommendations
[1] "Remove vignette sources from inst/doc; they belong in vignettes/."   
[2] "y of x.y.z version should be even in release"                        
[3] "Import clusterProfiler, stringr in NAMESPACE as well as DESCRIPTION."
[4] "Import utils, utils in DESCRIPTION as well as NAMESPACE."            
[5] "Add non-empty \\value sections to the following man pages:"          

$considerations
[1] "Using accessors; don't access S4 class slots via '@' in examples/vignettes."                     
[2] "Adding runnable examples to the following man pages which document exported objects:"            
[3] "Adding a NEWS file, so your package news will be included in Bioconductor release announcements."
[4] "Shortening lines; 179 lines (5%) are > 80 characters long."                                      
[5] "Indenting lines with a multiple of 4 spaces; 651 lines (19%) are not."

**Comment by pedrostrusso** [comment]
This is the result of the build attempt from Bioconductor: http://bioconductor.org/spb_reports/CEMiTool_buildreport_20170531132739.html

I suggest everyone to subscribe to our topic in their page: 
https://github.com/Bioconductor/Contributions/issues/386

It seems that there are 2 main errors: Helder needs to subscribe to the Bioconductor mailing list, and the dreaded "Object 'Stat' not found" error. I'll reopen the issue.

**Comment by pedrostrusso** [comment]
CEMiTool accepted on Bioconductor on August 1st, 2017. :) Closing issue.
