### ISSUE TITLE
Function examples

### ISSUE THREAD

**Issue by lecardozo** [csbl-usp/CEMiTool#17]
### Precisamos colocar exemplos na documentação das seguintes funções:
- cemitool.R
   - [x] expr_data
   - [x] sample_annotation
   - [x] filter_expr
   - [x] nmodules
   - [x] mod_colors
   - [x] save_files
- report.R
   - [x] generate_report
- visualization.R
   - [x] get_hubs
- enrichment.R
   - [x] read_gmt
- interactions.R
   - [x] include_interactions
- integrate.R
   - [ ] cemoverlap

**Comment by pedrostrusso** [comment]
I added examples to a few of the functions. However, since the methods have the "Usage" section, I wasn't sure if I needed to add examples to them. Also, I can't seem to update your checklist, @lecardozo, would I have to create another one each time I update a function's docs?

**Comment by lecardozo** [comment]
Nice!
I think there's no way for you to update the task list in the issue description.
Just add the functions you worked on here and I'll update it.

**Comment by pedrostrusso** [comment]
I've updated all of the functions except for cemoverlap(). Could you please look into this, @diolima ?

**Comment by csbl-usp** [comment]
@diolima updated the last function. Closing the issue.
