### ISSUE TITLE
Error in eval(expr, envir, enclos) : objeto 'Stat' não encontrado

### ISSUE THREAD

**Issue by pedrostrusso** [csbl-usp/CEMiTool#18]
Apparently it has to do with the sna package. Looking into it.

**Comment by pedrostrusso** [comment]
This error appeared during the Bioconductor build attempts. More details at:
http://bioconductor.org/spb_reports/CEMiTool_buildreport_20170531132739.html

**Comment by pedrostrusso** [comment]
I removed the ggnetwork package dependency. There should be no more issue now.

**Comment by briatte** [comment]
Dear all ~ FWIW, `ggnetwork` has just been (heavily) updated.
