### ISSUE TITLE
Can I use WGCNA to perform analysis based on the results of CEMiTool

### ISSUE THREAD

**Issue by YiweiNiu** [csbl-usp/CEMiTool#27]
Hello,

CEMiTool is a wonderful tool! I always used WGCNA before.

I want to do the following things based on CEMiTool's results:
* relating modules to external information, such as [the way](https://labs.genetics.ucla.edu/horvath/CoexpressionNetwork/Rpackages/WGCNA/Tutorials/FemaleLiver-03-relateModsToExt.pdf) in WGCNA
* exporting a network to a external visualization software such as Cytoscape, like [this](https://labs.genetics.ucla.edu/horvath/CoexpressionNetwork/Rpackages/WGCNA/Tutorials/FemaleLiver-06-ExportNetwork.pdf)

I don't know how to do these in CEMiTool, and I think a simple way to do is using functions in WGCNA. Can I do that? According to the paper of CEMiTool, the only difference between CEMiTool and WGCNA is beta selection: "[Once a β value is chosen, subsequent steps for creating modules follow standard WGCNA procedure.](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2053-1#Sec15)".

Or how to extract information needed from the results of CEMiTool if not using WGCNA? Thank you in advance!

Bests,
Yiwei Niu

**Comment by pedrostrusso** [comment]
Hi Yiwei, thanks for your interest in CEMiTool!

CEMiTool exports an eigengene values table (summary_eigengene.tsv), which you could use to relate to external information as shown in the page you linked. Also, CEMiTool also exports an edgelist table (interactions.tsv), which could be inserted into Cytoscape. Both these tables are obtained by using the "write_files()" function.
CEMiTool is in continuous development, so we'll be improving it and adding new functionality in the coming months, so thanks for the feedback!

**Comment by pedrostrusso** [comment]
Hi Yiwei, thanks for your interest in CEMiTool!

CEMiTool exports an eigengene values table (summary_eigengene.tsv), which you could use to relate to external information as shown in the page you linked. Also, CEMiTool also exports an edgelist table (interactions.tsv), which could be inserted into Cytoscape. Both these tables are obtained by using the "write_files()" function.
CEMiTool is in continuous development, so we'll be improving it and adding new functionality in the coming months, so thanks for the feedback!

**Comment by YiweiNiu** [comment]
Thank you for your reply!

I find the tables I need in the new version (1.4.0).

I used the genes and beta value selected by CEMiTool to run WGCNA and found their results were almost exactly the same (only several genes were allocated to different modules.)

I've got another question: which network type should I use, singed or unsigned? Both the defalut settings of CEMiTools and WGCNA are using 'unsigned' network now. But I found one developer of WGCNA said [he prefered signed network](http://www.peterlangfelder.com/signed-or-unsigned-which-network-type-is-preferable/). And also people said that [the difference is negligible](https://support.bioconductor.org/p/84835/). I've tried both in CEMiTool, but found the results were similar (from the ORA analysis of GO/KEGG). I don't know how to choose the "right" one. Do you have some experience on this issue, for example sample size, the research questions?

**Comment by csbl-usp** [comment]
Hi Yiwei,

There is no "right" answer for your question. It is really a matter of
preference. As long as you are describe in the methods of your paper which
type of network did you use and you are satisfied with the results, then it
is all good.

Best,

Helder

==
Helder Nakaya, Ph.D.
Assistant Professor

School of Pharmaceutical Sciences
University of Sao Paulo, Brazil

Computational Systems Biology Laboratory <http://csbiology.com/>

**Comment by YiweiNiu** [comment]
😂 OK, thank you for your reply!
