### ISSUE TITLE
expr0 {CEMiTool}

### ISSUE THREAD

**Issue by mhmjuliao** [csbl-usp/CEMiTool#29]
Hi there,
I have a data.frame with 274 obs and 5 var
After ""cem <- new_cem(expr0)""
the file has 4000 obs and 45 var
How can I see what's happening? Because ""head(expr0)" don't shows my IDs, it shows other names that I don't know what they mean.

Please, if someone could help me.

**Comment by pedrostrusso** [comment]
To clarify, expr0 is a demo expression object included in the package as an example. Therefore, when running `cem <- new_cem(expr0)`, we obtain a CEMiTool object with the expr0 object's characteristics. To avoid this, rewrite the expr0 object with your own data: `expr0 <- read.table("expression_data.tsv")`
