### ISSUE TITLE
module enrichment for numeric annotation

### ISSUE THREAD

**Issue by kaanokay** [csbl-usp/CEMiTool#34]
Hi,

I have a problem about annotation step for my data.
When I have made categorical annotation for my sample, I didn't come across any problem, but I want  use continuous variable instead of categorical variable to calculate module-trait association just like in WGCNA. Is this available for CEMiTool ?
I split my data two categories and generated module enrihment between them, therefore I want make that for my numerical categories.

Categorical annotation ;

SampleName Class
AD                       Parent
BD                       Parent
CM                      Children
IM                        Children

Above annotation worked to make module enrichment analysis between Parents and Children, but I want generate annotation like below and calculate module-trait association. How can I make this analysis with using CEMiTool ?

Numeric (continous) annotation ;

SampleName CARS 
AD                    40
BD                    38
CM                    24
IM                      22

Can you help me about that?

Thanks your good R package and interest,
Best regards,

**Comment by pedrostrusso** [comment]
Hi @kaanokay, this isn't offered in CEMiTool per se yet, but what you can do is obtain the eigengenes for your modules and then correlate them with your continuous trait of interest, as per the WGCNA method. You can obtain your eigengenes in a data.frame using the `mod_summary` function, as follows:

`eigengenes <- mod_summary(cem, method = "eigengene")`, 

where `cem` is your CEMiTool object generated after running the `cemitool` function.

**Comment by kaanokay** [comment]
I will try your the advise,
Thanks,
