### ISSUE TITLE
PPI Networks

### ISSUE THREAD

**Issue by kaanokay** [csbl-usp/CEMiTool#35]
Hi,

If I use default CEMiTool interaction file, then my result will be different than using of more comprehensive PPI files.
There are some databases like HitPredict which provide more comprehensive PPI files. Which should I use them ?  
What do you recommend me ? CEMiTool interaction file (almost 188.000 interactions) is enough or not for publication ?

Thanks,
Regards,

**Comment by pedrostrusso** [comment]
Hi @kaanokay, you should use whichever PPI file you think is best, the one provided in CEMiTool is merely an example.

**Comment by pangxueyu233** [comment]
@kaanokay Hi, have your worked it out ? recently, I also want to import a interaction file into formula.

**Comment by kaanokay** [comment]
Hi @pangxueyu233 ,
I used HitPredict database (http://hintdb.hgc.jp/htp/) for construction of PPI networks. You can download PPIs for any species which you want.
