### ISSUE TITLE
Can we visualise the position and degree of key genes optionally

### ISSUE THREAD

**Issue by pangxueyu233** [csbl-usp/CEMiTool#40]
It's a really impressive working, and I tried to use this pakages to mine more intersesting information in my data recently. And I got the standard outputs files successfully. But in the last step, interaction visulization, I want to show my interested genes' position in network and furthermore, I want to only show the gene network whose highest degree level is same to my interested gene. 
And for achieving the second thinking, I might work out by filtering the input interactions files, calculating the degree of each genes and filtering the highest genes and lowest genes.  did you think can I use that way to achieve that ?  
But that will be much better that we could select the key genes to display the position and degree of them. 
Thanks

**Comment by pedrostrusso** [comment]
Hi @pangxueyu233 thanks for using CEMiTool.
Yes, I think that if you're able to calculate each gene's degree, and then filter your input interactions file beforehand you should be able to get only the genes with the same degree as your gene of interest. 
Visualizing a gene of interest in the interaction network isn't currently in our development plan, but I'd be happy to review a pull request if you decide to try to implement these changes.
