### ISSUE TITLE
NAs in gene expression matrix

### ISSUE THREAD

**Issue by Carldeboer** [csbl-usp/CEMiTool#41]
Hi 
I have NAs in my gene expression matrix and it seems to be breaking cemitool with the following error:

```R
> cem <- cemitool(expressionIsolateGeneMat)
Error in matrixStats::rowVars(expr) : Argument 'x' cannot be logical.
```
It "works" when I replace all the NAs with 0s, but that's not really what I want to include there. 
```R
> expressionIsolateGeneMat2 = expressionIsolateGeneMat;
> expressionIsolateGeneMat2[is.na(expressionIsolateGeneMat)]=0;
> cem <- cemitool(expressionIsolateGeneMat2)
... works ...
```

Any advice on what I should be including in the NAs?  Ideally, any entries that are NA would just be ignored in the analysis.
Thanks!

**Comment by Carldeboer** [comment]
I have confirmed that I can't simply replace the cor function with one insensitive to NAs: 
```R
cor2 = function(x){cor(x, use="pairwise.complete.obs", method="pearson")}
cem <- cemitool(expressionIsolateGeneMat, cor_function = "cor2")
```

**Comment by pedrostrusso** [comment]
Hi @Carldeboer thanks for using CEMiTool, and sorry for taking so long to get back to you. 
Thanks for pointing this out, it should be working now. 
Best, 
Pedro
