### ISSUE TITLE
GSEA module association 

### ISSUE THREAD

**Issue by castvox** [csbl-usp/CEMiTool#43]
Hello, 

I am a new user and absolutely love the package. However, I noticed whenever I plot a GSEA module association graph it misses one module whenever I try to associate more than 10 modules.  I have also noticed this in one of the figures of the CEMITool paper in figure 8a.
![CEMITool](https://user-images.githubusercontent.com/56974873/67509916-07d2e380-f662-11e9-9548-956dadbcfaf0.png)

**Comment by pedrostrusso** [comment]
Hi @castvox, thanks for using CEMiTool.

This is actually intended behavior, as to not show modules with too many genes. You can override this behavior by increasing the `gsea_max_size` parameter to whichever number you want (including Inf, to allow any size module) in the `cemitool` function call.
