### ISSUE TITLE
Questions about constructing interaction network

### ISSUE THREAD

**Issue by Thegreatjoyce** [csbl-usp/CEMiTool#45]
Hi CEMiTool team, thanks for develop such a user-friendly tool. But I am not sure what file to provide to build the interaction network. Can you explained more?

**Comment by pedrostrusso** [comment]
Hi @Thegreatjoyce, thanks for using CEMiTool!

The interaction network should be a file simply containing pairs of genes in the rows, in columns named "Gene1" and "Gene2". You can find a bit more detail on file formats in the webCEMiTool tutorial page [here](https://cemitool.sysbio.tools/tutorial)
