### ISSUE TITLE
Question about module perservation

### ISSUE THREAD

**Issue by castvox** [csbl-usp/CEMiTool#46]
Hello CEMiTool team,

I appreciate your help with my previous questions and everything works perfectly! However, I was wondering if there was a "module preservation" equivalent function in CEMiTool.
I currently have a data set with 3 different "conditions"(condition-1, condition-2, condition-3). They each have a different number of replicates within them(condition-1=15 reps, condition-2=17 reps, condition-3= 18 reps). I am able to define the modules in the full data set (reference modules) but I was wondering if it was possible to perform a module preservation between my "reference" to the 
respective conditions to see how well the modules are preserved between each condition. Essentially I would like to see the statistics and 3 different networks showing the different connectivity between the conditions based on the reference modules. 

An example of this is from 
[https://www.frontiersin.org/articles/10.3389/fnsys.2017.00075/full](url)

![image](https://user-images.githubusercontent.com/56974873/68697137-3d296d80-054c-11ea-926f-9e3927ef21d1.png)

Thank you

**Comment by pedrostrusso** [comment]
Hi @castvox, I'm glad you're enjoying the package. Unfortunately, we currently have no plans to implement this functionality in the near future, but we'd be happy to review a pull request.
