### ISSUE TITLE
How many samples

### ISSUE THREAD

**Issue by benxiahu** [csbl-usp/CEMiTool#49]
Hi,
   I want to use this website to perform co-expression network analysis: https://cemitool.sysbio.tools/analysis. I just have 7 vs 7 samples. Can I use CEMiTool to perform co-expression network analysis?
Best,

**Comment by pedrostrusso** [comment]
Hi @benxiahu, thanks for your interest but unfortunately CEMiTool is designed to use with at the very least 18 samples for adequate statistical power.
