### ISSUE TITLE
CEMiTool error in  GSEA analysis: Error in `[.data.frame`(z_expr, , class_samples, drop = FALSE)

### ISSUE THREAD

**Issue by ruchiups** [csbl-usp/CEMiTool#50]
Hi , 
Cemitool runs fine with  6 modules selected. 
nmodules(cem_g)
[1] 6
My class column has 2 classes CLL/Normal. Get error when running GSEA-
cem_g <- mod_gsea(cem_g,verbose = TRUE)
Running GSEA
Calculating modules enrichment analysis for class CLL
Error in `[.data.frame`(z_expr, , class_samples, drop = FALSE) : 
  undefined columns selected

I also tried with - cem_g <- mod_gsea(cem_g,gsea_scale= FALSE, verbose = TRUE)
but get the same error

Can you please help with this error?

**Comment by pedrostrusso** [comment]
Hi @ruchiups thanks for using CEMiTool. This error tends to occur when the columns in the sample annotation file are factors. If you're using `read.table` to read your data, please try giving it the `stringsAsFactors = FALSE` option. Let me know if this works for you.

**Comment by ruchiups** [comment]
Thanks @pedrostrusso ! It worked.
It will be useful to capture this in help file somewhere, just so that you don't get this type of questions anymore :)
