### ISSUE TITLE
Issues with analysis on online CemitTool

### ISSUE THREAD

**Issue by ruchiups** [csbl-usp/CEMiTool#51]
Hi 
When I run analysis using Cemitool package on my desktop Rstudio it runs fine with automatic beta selection. 
But, using exactly the same expression and phenotype input files (in .tsv format) when I try to run the analysis on online CemiTool portal, get the following error-
Your analysis has failed with the following error: Error in .local(cem, ...): Sample annotation file does not contain all samples in expression file. Please input new sample annotation file using function sample_annotation();

I compared my input files to example files available from Cemitool tutorial and don't see a difference in format.

Please help.

**Comment by ruchiups** [comment]
@pedrostrusso 
 If I run using only expression file it does run but for some reason, it is not able to recognise the phenotype input file. Didn't have any such problem when running the package manually with the same input files.

**Comment by kemguru2020** [comment]
hello, 

I am also having the same problem. I get the following error when I upload my phenotype input file: Your analysis has failed with the following error: Error in `[.data.frame`(annot, , cem@class_column): undefined columns selected;

But the error doesn't come up when I use only the expression data

Kindly help with this error

thanks

**Comment by pedrostrusso** [comment]
@csbl-usp please assist with this issue

**Comment by pedrostrusso** [comment]
@kemguru I think your error is different from the one ruchips is getting, I believe all you have to do is make sure that your phenotype input data.frame doesn't contain factor columns (that is, convert them to strings).

**Comment by keiko12N256** [comment]
Hello,
I'm also having trouble with online CEMiTool.
Although my "phenotype" file contains all sample names and class, I get the below error.

"Your analysis has failed with the following error: Error in .local(cem, ...): Sample annotation file does not contain all samples in expression file. Please input new sample annotation file using function sample_annotation();"

Thank you in advance for your help😊

**Comment by pedrostrusso** [comment]
For issues with webcemitool, please use the following link: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2053-1/email/correspondent/c1/new
