### ISSUE TITLE
There were 6 pathways for which P-values were not calculated properly due to unbalanced gene-level statistic values

### ISSUE THREAD

**Issue by saramasarone** [csbl-usp/CEMiTool#53]
Hi, 
I am trying to run Cemitool on my dataset providing the expression data frame and the sample annotation data frame but I get an error saying that "There were 6 pathways for which P-values were not calculated properly due to unbalanced gene-level statistic values"

> expr <-data.frame(no_outliers)
> cem <- cemitool(expr, sample_annotation)
> cem <- mod_gsea(cem)
> cem <- plot_gsea(cem)
> show_plot(cem, "gsea")  

Any suggestion on what might be the problem?

**Comment by pedrostrusso** [comment]
Hi @saramasarone, thanks for using CEMiTool!
That error message comes from the fgsea package, which we use in CEMiTool to calculate GSEA, so I'm not too sure what could be causing it as well. Looking at the source code for the package [here](https://rdrr.io/bioc/fgsea/src/R/fgsea.R) this seems to happen when there are NA values in the p-values of the analysis, but I don't know what might cause them. Maybe try checking if your genes in your expression file and gmt file correspond with the same gene symbols, etc. It might be easier to contact fgsea's maintainers though. If you are still unable to fix it then, please let us know.

**Comment by saramasarone** [comment]
I see, thank you! I'll contact them!
