### ISSUE TITLE
No modules found

### ISSUE THREAD

**Issue by gabrieljmarques** [csbl-usp/CEMiTool#54]
Olá,
estou tentando rodar o pacote no R, porém quando insiro meus dados, retorna uma mensagem de que nao foram encontrados modulos.

> CEMiTool Object
> - Number of modules: 0 
> - Modules: null
> - Expression file: data.frame with 7171 genes and 18 samples
> - Selected data: 72 genes selected
> - Gene Set Enrichment Analysis: null
> - Over Representation Analysis: null
> - Profile plot: null
> - Enrichment plot: null
> - ORA barplot: null
> - Beta x R2 plot: null
> - Mean connectivity plot: null

> Could not specify the parameter Beta. No modules found.
> Unable to find parameter beta. Please check diagnostic plots with function diagnostic_report().

poderiam me ajudar, por gentileza?

abaixo segue o código utilizado

> cem <- cemitool(expr0, sample_annot, gmt_in, interactions=int_df, 
>                 filter=TRUE, plot=TRUE, verbose=TRUE)

**Comment by pedrostrusso** [comment]
Oi @gabrieljmarques obrigado por usar o CEMiTool.  Qual é a natureza dos seus dados? Se vc estiver utilizando dados de RNA-seq, verifique se você está usando dados normalizados por RPKM, FPKM ou similares - o importante é que não podem ser simples counts. Além disso, certifique-se de estar usando um número razoável de amostras; nós recomendamos um mínimo de 20. Dê uma olhada também no FAQ do WGCNA https://horvath.genetics.ucla.edu/html/CoexpressionNetwork/Rpackages/WGCNA/faq.html 

Não encontrar um valor de beta não necessariamente é um problema do pacote, simplesmente pode significar que seus dados não seguem a distribuição "scale-free" assumida pelo modelo da ferramenta.
