### ISSUE TITLE
CEMitools with negative PIC values

### ISSUE THREAD

**Issue by jasminelmah** [csbl-usp/CEMiTool#57]
Hi,

I am using single cell UMI abundance values that have been transformed into phylogenetic independent contrasts (PICs). PICs were designed to compare data points across species on a phylogeny, taking into account autocorrelation due to phylogenetic relatedness (see [Felsenstein (1985).](https://www.journals.uchicago.edu/doi/abs/10.1086/284325) ). If, for example, I was comparing the expression of two genes across different species, their expression may seem to be correlated but only because closely related species have a tendency to have a similar phenotype. So PICs allow you to identify "true" correlations between genes that are not due to phylogenetic relatedness.

I am currently treating cells as if they're species, having made a phylogeny of cells. Unlike normal count values, PIC values can be negative. However, these negative values should still show a correlation if there is covariance.

Can CEMitool handle negative values? Would CEMitool act "as expected" if I were to use PIC values?

Thanks for your help! I would be open to providing more in depth explanation if needed.

**Comment by pedrostrusso** [comment]
HI @jasminelmah CEMiTool was designed to work with microarray and RNAseq data, so there is no guarantee that your analysis will work "as expected". It's also not designed for working with negative values (which doesn't mean that it can't, I just don't know what would happen).
