### ISSUE TITLE
identifying a cell's gene modules

### ISSUE THREAD

**Issue by jasminelmah** [csbl-usp/CEMiTool#58]
I have two questions:

Is the sample tree just a distance clustering of the expression matrix? Or is it a clustering of the gene modules a cell possesses?

How do I find the mapping between gene modules and cells (ie which cells possess which gene modules)? I am guessing I'm missing something simple. I'm working in R and not the online GUI.

Thank you for your help!

**Comment by pedrostrusso** [comment]
The sample tree plot is a distance clustering between samples in the expression matrix. 
I'm not sure what you're considering your cells to be, but you can find which genes are in which modules by using the `module_genes` function.

**Comment by jasminelmah** [comment]
I - sorry, I consider each cell a sample. Is it possible to identify which modules are present in each sample?

**Comment by pedrostrusso** [comment]
Hi @jasminelmah, all samples are used to identify the modules, thus there are no "sample-specific" modules.

**Comment by jasminelmah** [comment]
Thanks @pedrostrusso I'll give that a try.
