### ISSUE TITLE
Interpreting fGSEA plots

### ISSUE THREAD

**Issue by phoebe460** [csbl-usp/CEMiTool#61]
Hello CEMiTool developers,

First off, thanks for making this great tool! It's been really cool to use and it hasn't been too difficult to implement and am getting some interesting results. So I was wondering if you can help me interpret the following plot I made using my raw, filtered counts from my RNA-seq data set with the following code: 

```cem <- cemitool(counts_expr, sample_annot_expr, gmt_in_GO, interactions=int_df, apply_vst = TRUE, filter=TRUE, filter_pval = 0.05, plot=TRUE, verbose=TRUE, ora_pval = 0.05)```

![image](https://user-images.githubusercontent.com/56165012/108536999-f28bba80-7291-11eb-80e2-67047907de21.png)

I had a few questions regarding the plot:
1) What does the size of the circles for each module mean? Does it pertain to strength of the expression characterized by each classes per module? 
2) Does the red and blue colors mean up-regulated and down-regulated expression for the different classes in each of those modules?
3) So for example, in my plot above, does that mean class A79V has very strong up-regulated expression due to the dark red color and large circle?

Also, I was looking at your paper and it says the following: "genes from co-expression modules
will be treated as gene sets and the z-score normalized expression of the samples within each phenotype will be treated as rankings on the analysis." Could you explain this further? Does fGSEA take into account differential analysis between the different classes or does it treat each class separately instead? 

If you can clarify my interpretation of the fGSEA analysis from CEMiTool, then that would be awesome. 

Thank you! Much appreciated.

-Phoebe

**Comment by pedrostrusso** [comment]
Hi @phoebe460 thanks for the kind comments, I'm glad you're liking CEMiTool!
As for your questions:
1) The circle size relates to the NES exactly the same as the circle color
2 and 3) Yes

About your other questions, that quote means only that CEMiTool will use the genes in your modules as the gene sets, and see if the expression values in each module/phenotype pair are particularly overexpressed or underexpressed using the standard GSEA protocol. It treats each class separately i.e. it doesn't take into account any sort of differential expression analysis. Hope this helps!

**Comment by phoebe460** [comment]
Hi Pedro,

Okay, thank you so much for your clarification. That makes a lot more sense! I also have another question, but this time regarding the co-expression network modules I get. Here is an example of a plot I get:

![Module1_Interactions](https://user-images.githubusercontent.com/56165012/108605345-6d270980-7368-11eb-91a3-d5835a527a28.png)

So how do we know whether the hub genes are up or down regulated? Since this is associated to module 1 in the fGSEA plot I get before, would I assume all the hub genes are overexpressed in class A79V, and then they are all underexpressed in classes N141I, V717I and NDC? Or are those colors only relevant to the pathways enriched from ORA analysis? 

Also, I saw in another [post](https://github.com/csbl-usp/CEMiTool/issues/44) about inputting the module gene data as an edge list format and exporting that into Cytoscape using the following code I made:

``` 
#Example using module M1
m1genes <- module_genes(cem, "M1")["genes"]
m1genes <-unlist(m1genes)
m1adj <- adj_data(cem)[m1genes, m1genes]

#To put the data in edge list format for Cytoscape, you can melt it using reshape2:
resm1 <- reshape2::melt(m1adj)

#Write the data in edge list format for module 1
write.csv(resm1, file="~/Desktop/CEMitool/Cytoscape/resm1.csv", row.names = F) 
```
So when inputting this into Cytoscape, how would I go about doing that? I know I would input the .csv file as a ```network file``` which looks like below:

<img width="248" alt="Screen Shot 2021-02-17 at 3 52 14 PM" src="https://user-images.githubusercontent.com/56165012/108605570-ad3abc00-7369-11eb-85a2-90121b3daf8c.png">

but do you recommend what to do afterwards? I am a beginner when it comes to using Cytoscape, so if you have any suggestions/advice of how to export these edge list format files into that program, then that would be much appreciated.

Thank you for your help and enjoy the rest of your weekend!

Best
Phoebe

**Comment by pedrostrusso** [comment]
Hi @phoebe460, 
**"So how do we know whether the hub genes are up or down regulated?"**
Currently this isn't implemented in CEMiTool, though it would be a great pull request to submit (;
**Since this is associated to module 1 in the fGSEA plot I get before, would I assume all the hub genes are overexpressed in class A79V, and then they are all underexpressed in classes N141I, V717I and NDC? Or are those colors only relevant to the pathways enriched from ORA analysis?**
If your module M1 is overexpressed in class A79V, you'd probably be right to assume that your hub genes are overexpressed as well, since they are the major drivers behind module expression, but don't forget that at least some of them might be strongly negatively correlated with the module, depending on if the network you created is signed or not .  
About Cytoscape, sorry, but I really don't know how to use it either lol I just knew that you could do use an edgelist to create networks.

**Comment by phoebe460** [comment]
Hi @pedrostrusso, first off thank you so much for answering all my questions. Actually I changed the cemitool code to add the ``` network_type = "signed"``` parameter, which actually gave me more informative results. Here is the complete code below:

```
cem_interactions_ECC_signed <- cemitool(counts_expr, sample_annot_expr, gmt_in_ECC,
interactions=int_ECC_df, apply_vst = TRUE, filter=TRUE, filter_pval = 0.05, plot=TRUE, 
verbose=TRUE, ora_pval = 0.05, network_type = "signed")
```

So thank you for suggesting that. It makes more sense to incorporate strongly negative as well as strongly positive correlated hub genes within each module, so I really appreciate that. Also I would be happy to suggest a pull request to account for up and down-regulated hub genes. 

So, I have another additional question regarding co-expression networks:

I have this co-expression network below I made using my own set of interaction features (used EnCODE/ChEA database) and it says there are too many overlaps. Is there a way to change the "max.overlaps" so I can see the remaining 9 unlabeled data points? Where in the code can I change that?

<img width="931" alt="Screen Shot 2021-03-02 at 9 26 49 AM" src="https://user-images.githubusercontent.com/56165012/109689383-15dc2280-7b3a-11eb-962d-abf7b4c92664.png">

If you can let me know how to do this, then that would be awesome. Also I do have some other questions regarding the implementation of the ORA and PPI-networks from GeneMania, but I can definitely up another issue regarding this. Thanks again Pedro! :)

**Comment by pedrostrusso** [comment]
Hi @phoebe460, I'm not 100% sure, but it seems you can set `options(ggrepel.max.overlaps = Inf)` to avoid this issue (from the [ggrepel documentation](https://ggrepel.slowkow.com/articles/examples.html#always-show-all-labels-even-when-they-have-too-many-overlaps-1)). I haven't tried it myself, but maybe it will help. Please let me know if it doesn't work.

**Comment by phoebe460** [comment]
Hi, yes it looks like ```options(ggrepel.max.overlaps = Inf)``` did help, and my unlabeled points did label this time. See updated network below. 

![M1_ECC_Interactions](https://user-images.githubusercontent.com/56165012/110022683-1531c080-7ce1-11eb-8043-add65d0fda70.png)

Thank you again @pedrostrusso for all your help. If I have anymore questions, will certainly let you know. :)
