### ISSUE TITLE
troube in cemitool

### ISSUE THREAD

**Issue by cqneosun** [csbl-usp/CEMiTool#63]
Error in if (a < 0) stop("Argument 'a' must be real and nonnegative.") : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In sqrt(expr/r) : NaNs produced

**Comment by cqneosun** [comment]
![image](https://user-images.githubusercontent.com/28380395/109406168-de426e80-79b1-11eb-9dee-a667c3792d43.png)

**Comment by cqneosun** [comment]
cem <- cemitool(ESCArna, ESCAlin,gmt_in, interactions=int_df1, apply_vst =TRUE,filter=TRUE, plot=TRUE, verbose=TRUE)

**Comment by cqneosun** [comment]
rnaseq data almost seems not fit norm distribution,  so cor.method pearson  should not be feasible.
Is this right?

**Comment by cqneosun** [comment]
![image](https://user-images.githubusercontent.com/28380395/109408880-9f6be300-79c8-11eb-81df-b332688ae35b.png)

**Comment by cqneosun** [comment]
when i set filter=FALSE,it works.But excess computer expend

**Comment by cqneosun** [comment]
when i set filter_pval = 0.05,it also works.

**Comment by pedrostrusso** [comment]
Hi @cqneosun It seems you've placed several issues here, so I'm not sure what I'm supposed to make of all this, but, answering your actual question, yes, I think you might get more meaningful results if you set method = "spearman". Then again, maybe run both and see which result seems more meaningful to you. As for your filtering issue, I'd advise you to ask the pracma package's developers as to what the error means.

**Comment by cqneosun** [comment]
> Hi @cqneosun It seems you've placed several issues here, so I'm not sure what I'm supposed to make of all this, but, answering your actual question, yes, I think you might get more meaningful results if you set method = "spearman". Then again, maybe run both and see which result seems more meaningful to you. As for your filtering issue, I'd advise you to ask the pracma package's developers as to what the error means.

Thanks
