### ISSUE TITLE
why some module with empty GSEA NES and p value?

### ISSUE THREAD

**Issue by cqneosun** [csbl-usp/CEMiTool#64]
![image](https://user-images.githubusercontent.com/28380395/109449188-c2f36400-7a82-11eb-8b55-4ee8fd34d168.png)

**Comment by pedrostrusso** [comment]
Hi @cqneosun would you mind sharing your data so I could take a look?

**Comment by cqneosun** [comment]
> Hi @cqneosun would you mind sharing your data so I could take a look?

Sure.share me your email

**Comment by pedrostrusso** [comment]
pedrostrusso at gmail dot com

**Comment by cqneosun** [comment]
I have sent the data to your tutor's email:hnakaya<hnakaya@usp.br>
Please check it

**Comment by pedrostrusso** [comment]
Hi @cqneosun, sorry for taking so long to reply. Unfortunately, I am unable to run your data on my pc, as it's too big. As such, please try running the [code ](https://github.com/csbl-usp/CEMiTool/blob/master/R/enrichment.R)for the mod_gsea function yourself step-by-step to try to understand where the problem might be. I'd suspect you're getting NA values for some reason in your enrichment, but I can't be sure. Please let me know if you find anything.
