### ISSUE TITLE
ORA and PPI networks Clarification

### ISSUE THREAD

**Issue by phoebe460** [csbl-usp/CEMiTool#65]
Hi CEMiTool Developers,

I just had a few questions regarding the implementation of ORA (Over Representation Analysis) and using the PPI networks from GeneMania.

1) When creating the algorithm behind using ORA, were there any background genes used in the process when calculating which pathways/terms are significant? I was reading in your paper that you used the hypergeometric test and I've personally used this test before using the tmod package but took into account background genes compared against genes that are up and down-regulated, so I was just wondering.

2) I also read in your paper that you used PPI networks from GeneMania. I was just wondering if you used all the data from GeneMania or just the protein-protein physical interactions (PPI) themselves? Would there supposedly be a way to merge lets says gene symbols with edge weights, and create an interaction file from that? 

Anyways, just curious that's all. Again, if you would be willing to clarify this for me, then that would be awesome.'

Thank you again and have a good rest of your day.

Best,
Phoebe

**Comment by pedrostrusso** [comment]
Hi @phoebe460, 

1. Background genes are all genes in your gmt file; the hypergeometric test is then applied (via the `clusterProfiler::enricher` function) to the genes in your module against these background genes.
2. We used the PPI themselves. I'm not sure what you mean by merging gene symbols with edge weights, but CEMiTool will accept anything as long as its a 2-column file with gene1 in one column and gene2 in the other, so feel free to experiment.

Hope this helps

**Comment by phoebe460** [comment]
Ok sounds good. Your comments were quite helpful! I am planning to experiment with other types of interaction files by combining the interactions from GeneMania with some other TF motif databases I am interested in, and see where that leads me. Of course, I will make sure it is a 2 column gene file. Thanks for your comments, @pedrostrusso! Much appreciated.
