### ISSUE TITLE
what does the file selected genes.txt mean?

### ISSUE THREAD

**Issue by cqneosun** [csbl-usp/CEMiTool#67]
An unsupervised filtering method based on the inverse gamma distribution (Additional file 1: Text) will then select the genes used in the analyses(copy from your paper)

In my anlaysis,the number of selected genes(28) much less than of genes in each module.

I infer all input genes are used when conduct the module.The selected genes are used when conduct ppi interaction network.
Is this right?

**Comment by pedrostrusso** [comment]
Hi @cqneosun, actually, the selected_genes.txt file is supposed to only show the genes selected for your module, that is, genes that passed the filter (if used). It seems that the function outputting the file has a bug, I'll be fixing it tonight I think, and should be up until friday on Bioconductor. Thanks for bringing it to my attention. 
If you want to get the genes showing in your interactions plot, you can use the `get_hubs` function. As the name states, this function will give you your hub genes, that is, your most highly connected genes per module.
