### ISSUE TITLE
Changing Colors When Plotting Interaction Networks for Multiple Modules

### ISSUE THREAD

**Issue by phoebe460** [csbl-usp/CEMiTool#69]
Hi @pedrostrusso,

I hope all is well! I was just wondering if there is a way to change the color for each of the interaction networks displayed after running CEMiTool? Is there a way to change the color after plotting such interactions? I tried looking at the help documentation for the ```plot_interactions()``` function in R but I couldn't find any additional parameters that would perform this. If you can let me know how to approach this, then I would really appreciate it. Thank you so much!

All the best,
Phoebe

**Comment by pedrostrusso** [comment]
Hi @phoebe460, yes and no. There isn't currently an implemented way to do this, but you can "hack" it by playing around with something like the following code. Here, `name` should be the module you want, and `color` the HEX code of the color you want.

    name <- "M1"
    color <- "#00FFFFFF"
    hubs <- get_hubs(cem, n=10)

    CEMiTool:::plot_interaction(ig_obj=cem@interactions[[name]],
                 n=10, color=color, name=name,
                 mod_genes=module_genes(cem, name)$genes,
                 coexp_hubs=hubs[[name]])
