### ISSUE TITLE
Issues when calling diagnostic_report from within another markdown

### ISSUE THREAD

**Issue by komalsrathi** [csbl-usp/CEMiTool#70]
I am trying to run cemitool and diagnostic_report from within an R markdown document. Below is a reproducible example:

**test.Rmd**

    ---
    output: 
      flexdashboard::flex_dashboard:
        orientation: rows
    ---
    
    ---
    title: Test
    ---
    
    ```{r include=FALSE, echo=FALSE}
    knitr::opts_chunk$set(comment = NA)
    ```
    
    
    ```{r load_libraries}
    library(CEMiTool)
    ```
    
    ```{r cemitools}
    # run cemitool
    cem = cemitool(expr = expr0, annot = sample_annot)
    
    # run diagnostic report
    diagnostic_report(cem = cem, directory = 'cemitools_output', force = T)
    ```
When I knit the `test.Rmd` file, it generates the output `diagnostics.html` under `cemitools_output` directory in the working directory. However, it does not generate `test.html` as it should. Instead it throws the following error:

    pandoc: /Users/rathik/Desktop/Tests/markdown/cemitools_output/diagnostics_files/figure-html/sample_tree_plot-1.mb.png: openBinaryFile: does not exist (No such file or directory)
    Error: pandoc document conversion failed with error 1

So, `diagnostic_report` runs fine but it causes conflicts and prevents the parent markdown to be knit into an html document. Is there a solution for this?

**Additional info:**

```
> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.0.4      htmltools_0.5.1.1   tools_4.0.4         flexdashboard_0.5.2 yaml_2.2.1          tinytex_0.29       
 [7] rmarkdown_2.7       knitr_1.31          jsonlite_1.7.2      digest_0.6.27       xfun_0.21           rlang_0.4.10       
[13] evaluate_0.14 
```

**Working directory info:**

```
➜  pwd
/Users/rathik/Desktop/Tests/markdown

➜  tree .
.
├── cemitools_output
│   └── diagnostics.html
└── test_cemitools.Rmd

1 directory, 2 files
```

**Comment by pedrostrusso** [comment]
Hi @komalsrathi I'm afraid I'm not much of an expert with rmarkdown, so I don't know how to help you much, since you said that `diagnostic_report` is working fine. It seems there is an error when generating the sample tree plot, can you confirm that the plot is really not being created?

**Comment by komalsrathi** [comment]
@pedrostrusso Actually all the outputs are generated perfectly fine, the issue is that when I call `diagnostic_report` or even `generate_report` from within another markdown, the parent markdown is not getting generated which otherwise generates fine. I will create a dummy markdown with the same YAML header as the CEMiTool markdowns and see if that is causing an issue. Give me a few mins and I will close it here and open this issue in https://github.com/rstudio/rmarkdown.

**Comment by pedrostrusso** [comment]
Ah, I see. Cool, let me know if it ends up being an issue with CEMiTool for whatever reason.

**Comment by komalsrathi** [comment]
@pedrostrusso sorry for the confusion, issue pertains to rmarkdown. Closing it here.
