### ISSUE TITLE
how to  infer the hub gene ?

### ISSUE THREAD

**Issue by cqneosun** [csbl-usp/CEMiTool#71]
![image](https://user-images.githubusercontent.com/28380395/111871944-b1d5ad00-89c7-11eb-9013-5a1e1c7a7248.png)

How to explain the hub gene in paper? why set number 5 to the correlation hub ,while 10 for interaction?How to explain the hub gene of two category.
I think the network should name coexpression network rather than PPI network.Is this right?

**Comment by cqneosun** [comment]
![image](https://user-images.githubusercontent.com/28380395/111872059-61ab1a80-89c8-11eb-94ba-2b2772f6fb00.png)

**Comment by cqneosun** [comment]
![image](https://user-images.githubusercontent.com/28380395/111906446-93d18080-8a8b-11eb-9039-9dc004543870.png)

**Comment by pedrostrusso** [comment]
As stated in the help file you linked, the hubs are the genes with highest connectivity. You can set the method to adjacency or kME. Yes, I see the number in the package is inconsistent, it was changed after the package was launched. Even if that weren't the case, you can still set whatever number you want using the `n` argument. 
I'm glad you're showing such an interest in our tool, but I can't help but feel that at this point you're just nitpicking, Please keep in mind that I maintain this package in my free time, so I would appreciate it if you respected my time by being a bit more selective when opening issues here, especially considering how unappreciative and rude you have been.

**Comment by cqneosun** [comment]
It's just a consultation question not aganist you .Sorry to interupt you.

**Comment by cqneosun** [comment]
I rely on this tools for my graduation in a rush.maybe I ask question in a improper manner.I applogize for my rudeness.

**Comment by cqneosun** [comment]
I appreciate for your help
