### ISSUE TITLE
nmodules(cem) says I have 3 modules but I only see 2 plotted on the GSEA heatmap

### ISSUE THREAD

**Issue by ashaypatel** [csbl-usp/CEMiTool#73]
Hello, when I use cemitool() I get 3 modules. However, the GSEA heat map (in the html report) only shows two modules.
Then I ran:
`cem <- mod_gsea(cem)`
`cem <- plot_gsea(cem)`

which gives me the warning:
`Warning messages:`
`1: In fgseaMultilevel(...) :
  There were 1 pathways for which P-values were not calculated properly due to unbalanced (positive and negative) gene-level statistic values.`
`2: In fgseaMultilevel(...) :
  There were 1 pathways for which P-values were not calculated properly due to unbalanced (positive and negative) gene-level statistic values.`
`3: In fgseaMultilevel(...) :
  There were 1 pathways for which P-values were not calculated properly due to unbalanced (positive and negative) gene-level statistic values.`
`4: In fgseaMultilevel(...) :
  There were 1 pathways for which P-values were not calculated properly due to unbalanced (positive and negative) gene-level statistic values.`

Could this be responsible for me not seeing all three modules on the GSEA heatmap? If so what should I do to see all three modules?

Thanks

**Comment by pedrostrusso** [comment]
Hi @ashaypatel, the GSEA plot will only show modules which are enriched in at least one class. You are right though, it could be that the warning you're seeing is the reason why your third module isn't being enriched, and therefore, not showing in the plot. I don't know however if there is anything you can do about it, it might be best to open an issue in the fgsea repo.

**Comment by ashaypatel** [comment]
Turns our the issue is with gsea_max_size in cemitool(). The default value for this argument is 1000 and I had a module that was >1000 genes. This has resolved the issue. Thank you for your help!
