### ISSUE TITLE
Clarification request on module significance in GSEA,ORA

### ISSUE THREAD

**Issue by ruchiups** [csbl-usp/CEMiTool#75]
@pedrostrusso 
Will be grateful if you can please clarify the following-
In Cemitool analysis, sometimes the modules which are significant in GSE analysis don't seem to have any significant pathway in the PRA analysis, whereas some modules which are not significant in GSEA do have significant pathways in the ORA analysis.

Thanks in advance!

**Comment by ruchiups** [comment]
PS: I am wondering about the biological relevance of the modules with significant activity, hence the question.

**Comment by pedrostrusso** [comment]
Hi @ruchiups, essentially the ORA analysis tells you what pathways, etc the genes in your module are related to, while the GSEA analysis will tell you which modules (and in which experimental groups) are significantly expressed in your data. Hopefully that makes sense.

**Comment by ruchiups** [comment]
@pedrostrusso, thank you very much for responding!
Individually what each analysis does is clear. My question is when crosslinking the evidence,  so is my interpretation correct that if a module that is significantly expressed in say experimental group in GSEA analysis may not be biologically relevant if no pathways are enriched for the genes in that module? Because that is what I sometimes see and I mostly run 'signed' network though have seen this in both 'signed ' and 'unsigned' .

**Comment by pedrostrusso** [comment]
@ruchiups yes, I think so. And the contrary should be true as well, a module's genes can be highly related to a specific pathway according to the ORA analysis but that module might not be significantly expressed in your data.
