### ISSUE TITLE
NA values to some modules

### ISSUE THREAD

**Issue by lukais-i0han** [csbl-usp/CEMiTool#77]
Hi,

When running the function mod_gsea(), I found the following error:

In fgseaMultilevel(...) :
  There were 2 pathways for which P-values were not calculated properly due to unbalanced (positive and negative) gene-level statistic values. For such pathways pval, padj, NES, log2err are set to NA. You can try to increase the value of the argument nPermSimple (for example set it nPermSimple = 10000)

How can I solve this error?

Thanks

**Comment by pedrostrusso** [comment]
Hi @lukais-i0han, as discussed in #73, that can happen if you have modules above `cemitool`'s (or `mod_gsea`'s) `gsea_max_size` limit of 1000. Please try increasing the value and see if it solves your problem.

**Comment by lukais-i0han** [comment]
Hi, @pedrostrusso. I alredy incresead the gsea_max_size and I still got the same error.

**Comment by pedrostrusso** [comment]
I'm sorry to hear that. I don't know why this error could be happening, but it's definitely related to the fgsea package, so you might have more luck asking at their repo and seeing if your data correspond to some kind of "corner case".

**Comment by lukais-i0han** [comment]
Hi, @pedrostrusso. After some research, I found that modules with a higher content of genes with higher expression when compare to control can not have the NES value estimated by GSEA. The solution is to run the GSEA algorithm alone, changing the "nperm" to a higher value (1000,10000, and so on) and then incorporate this result to CEMitool object. This works for me.
Thanks again for your help.
