### ISSUE TITLE
Trouble interpreting differences in hub genes from interaction networks.

### ISSUE THREAD

**Issue by kylepalos** [csbl-usp/CEMiTool#78]
Hello,

First off, thank you for writing and maintaining CEMiTool, it has been very helpful for my research. I believe this issue also relates to [issue # 19](https://github.com/csbl-usp/CEMiTool/issues/19). My question concerns the differences in the ways that hub genes are annotated from the interaction network. I can't find an explanation of what the differences are in Hub annotations between "Interaction", Co-expression", and "Co-expression + Interaction" that I've been able to understand.  All of the labeled genes in the plot below are in M5 of my module.tsv output file. Wouldn't this suggest that they should all be "Co-expression + Interaction" to some degree as a hub gene, or am I misinterpreting?

I looked through the closed issues that had to do with interaction networks, but I could not find what I was looking for. If I missed something, please let me know.

Thank you again for your package, and your assistance. Please let me know if you need any additional information.

![image](https://user-images.githubusercontent.com/56089443/120402900-08c8fe00-c2f8-11eb-9faf-d233467f20d4.png)

**Comment by pedrostrusso** [comment]
Hi @kylepalos thanks for the kind words and sorry for taking a bit to get back to you. 
I admit it's a bit confusing at first, but the way it works is: blue is if your gene is a hub considering edges in your module only, green is if it is a hub considering both your module and interaction file edges, red if it is a hub in the interaction file edges only. In other words, being in the module or the interaction file is not enough, they must be **hubs** in both to warrant the green color. Does that make sense?

**Comment by kaanokay** [comment]
Hi @pedrostrusso,

Briefly, If a hub gene is green, it means that this gene is hub in both my module and interaction database, right? And we should focus on green ones to interpret our results? To sum up, blue ones are module hub genes, red ones are interaction database hub genes, but green ones are hubs in both our module and interaction database. 

Thank you for your interest.
Best.
