### ISSUE TITLE
Annotating neighboring genes in hub gene networks

### ISSUE THREAD

**Issue by phoebe460** [csbl-usp/CEMiTool#79]
Hello Pedro,

I hope everything is going well. I am currently in the process of summarizing my results using CEMItool, and I was just wondering if there is a way to annotate the neighboring genes (i.e. other nodes) in the PPI networks that are outputted after performing the signed interaction network analysis? I was primarily interested if there were any genes apart from the hub genes that can reveal some biological meaning to my results. See examples in photo below highlighted in light green. 

<img width="713" alt="Screen Shot 2021-06-29 at 12 40 00 PM" src="https://user-images.githubusercontent.com/56165012/123857649-70fb0780-d8d7-11eb-9997-ec5c8a44eb58.png">

If there is a way that these genes can be annotated, then that would be super helpful.

Thanks,
Phoebe

**Comment by pedrostrusso** [comment]
Hi @phoebe460, I'm happy to see you're still using CEMiTool. Unfortunately, there currently isn't a way to annotate those neighboring genes. You can try playing around with `interactions_data(cem)` and `plot_interactions(cem)` to come up with your own function, but I don't think it would be too straightforward.
