### ISSUE TITLE
how to obtain the mouse protein-protein interaction file？

### ISSUE THREAD

**Issue by thekingofall** [csbl-usp/CEMiTool#81]
Hello, I want to know how to obtain the mouse protein-protein interaction file. In your case, only the human protein-protein interaction file is provided. I used the mouse protein-protein interaction file on the string database, but this file can only cover about 5000 genes. So I want to know if you have a larger-scale mouse protein-protein interaction file or access to it?

**Comment by pedrostrusso** [comment]
Hi @thekingofall unfortunately, we have no interaction data to provide. Even the human PPI data is only an example and shouldn't be used for actual analyses. The original file was obtained from GeneMANIA, so maybe you could look there.
