### ISSUE TITLE
Deciphering PPI network

### ISSUE THREAD

**Issue by kphelan13** [csbl-usp/CEMiTool#84]
Hello!

Thank you for developing this wonderful tool, I had a hard time performing WGCNA on my own and CEMiTOOL has been amazing. My question is in regards to the protein-protein interaction network. I understand that hub genes are colored regarding their origin (ie if they are hub genes from the module or from the interaction network). I was wondering if you could explain this distinction; in other words, why are some genes only present in modules or only present in the uploaded interaction data, but not present in both? I was under the assumption that the interaction network was built off of the coexpression modules, so wouldn't the genes inherently be present in both datasets?

**Comment by pedrostrusso** [comment]
Hi @kphelan13 thanks for the kind words. It depends on what you put in your interactions file. If you tell CEMiTool that a specific gene in your module interacts with genes X, Y and Z not in your module, they will show in the plot (as long as they are hub genes). Maybe take a look at #78 and see if it helps.

**Comment by kphelan13** [comment]
Thank you, that makes sense. One last question: is there any order to the "modules_genes" table? I would like to take the top 100 most correlated genes for each module and use another tool for pathway analysis if possible.

**Comment by kphelan13** [comment]
I figured it out. For those wondering, you can use the `get_hubs` function to find the most connected genes per module. My example code is below for those who are interested. 

`hubs <- get_hubs(cem, "all", "kME")
write.csv(hubs$M1, file = "M1_connectivity.csv")
write.csv(hubs$M2, file = "M2_connectivity.csv")
write.csv(hubs$M3, file = "M3_connectivity.csv")
write.csv(hubs$M4, file = "M4_connectivity.csv")
write.csv(hubs$M5, file = "M5_connectivity.csv")
write.csv(hubs$M6, file = "M6_connectivity.csv")`
