### ISSUE TITLE
Beta value not found

### ISSUE THREAD

**Issue by brettChapman** [csbl-usp/CEMiTool#86]
Hi

I'm currently running Cemitool on 20 different transcriptomes, and for about half of them I'm getting a Beta value not found error.

I've tried multiple different ways to get around this problem using different parameters (bicor, cor, pearson, spearman, different rank methods, VST on/off etc), and filtering the expression matrix before-hand (i.e. removing genes with MAD values of 0), but it appears I'm stuck with only half of the results from my pan-transcriptome analysis as nothing seems to help.

Is it possible to set a beta value manually, even though it may not be optimal? Or perform some other kind of filtering on my expression matrix before-hand?

Thanks

**Comment by pedrostrusso** [comment]
Hi @brettChapman yes, it's possible, you can use the `set_beta` argument to manually define a beta value, or the `force_beta` argument to define a beta according to item 6 in the [WGCNA FAQ](https://horvath.genetics.ucla.edu/html/CoexpressionNetwork/Rpackages/WGCNA/faq.html)
