### ISSUE TITLE
Output of hierarchical clustered modules and eigengene plots

### ISSUE THREAD

**Issue by brettChapman** [csbl-usp/CEMiTool#87]
Hi

I was wondering if there is a way to get a dendrogram plots of modules and eigengenes, as can be done directly with WGCNA like in this tutorial: https://horvath.genetics.ucla.edu/html/CoexpressionNetwork/Rpackages/WGCNA/Tutorials/FemaleLiver-02-networkConstr-man.pdf

I'm presenting my findings, and I'd like to illustrate exactly how the modules are determined through a few additional plots.

If this isn't already built into or hidden in the code of CemiTool, could you please point me to which R scripts I could modify to add such functionality.

Thanks.

**Comment by pedrostrusso** [comment]
Hi @brettChapman this isn't implemented in CEMiTool, but you can get there with a bit of work: in the `find_modules` function you'll find the `cutTreeDynamic` function implemented similarly to the tutorial you linked to. Also, in the `get_merged_mods` function, you'll find the similar module merging step if you'd rather make the dendrogram after that step. The three functions can be found [here](https://github.com/csbl-usp/CEMiTool/blob/cb17b421460afe939ef7a2991ea6e72c69a91666/R/modules.R).
Hope this helps.
