### ISSUE TITLE
How to calculate logFC and p-value of co-expressed modules across different samples?

### ISSUE THREAD

**Issue by kaanokay** [csbl-usp/CEMiTool#88]
Hi @pedrostrusso,

I was wondering whether it is possible to obtain logFC and p-values of each co-expressed module across different samples. I think it should be pretty similar with differentially expressed genes (DEGs) mentality, but how to calculate them? Do you have recommendation for that?

Best regards.

**Comment by pedrostrusso** [comment]
Hi @kaanokay unfortunately there is currently no such functionality in CEMiTool. Maybe you could try something like separately creating your modules for each of your sample groups and comparing the module eigengene values between them? It might be difficult to find which modules are related to each other, though.

**Comment by kaanokay** [comment]
Hi @pedrostrusso,

Thank you so much for your quick reply. I'll try your recommendation. 

Bw.

**Comment by pedrostrusso** [comment]
Something like that; as stated in the [WGCNA paper](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-9-559), "The eigengene E can be thought of as a weighted average expression profile."

**Comment by kaanokay** [comment]
Thank a lot.
