### ISSUE TITLE
Missing interaction network for module

### ISSUE THREAD

**Issue by NickFiore-1** [csbl-usp/CEMiTool#89]
Hi Pedro, thanks for the extremely helpful package! 

My cem() analysis results in six modules (M1-M5 and Not.Correlated). All GSEA analyses are performed and reported for each module. Though, only M1-M4 modules have a corresponding interaction network, M5 is missing. M5 is interesting to us since M1 and M5 are the only modules with significant GSEA pathways. 

![Screenshot (114)](https://user-images.githubusercontent.com/60767620/153504076-ace86e76-2885-4ef5-9697-a4e4e13fe677.png)

When I try to open cem@interactions[["M5"]] I get:
Error in adjacent_vertices(x, i, mode = if (directed) "out" else "all") : 
  At iterators.c:759 : Cannot create iterator, invalid vertex id, Invalid vertex id

I also noticed M5 is absent at cem@interaction_plot[["M5"]]

Thank you for the help in advance!
Nick

**Comment by pedrostrusso** [comment]
Hi @NickFiore-1, thanks!
Does the error appear if you run `cem <- plot_interactions(cem)` ? 
Also, please make sure if you have "weird" gene names in your interactions file or expression file, it looks like the underlying `igraph` function is complaining about the vertex name.

**Comment by NickFiore-1** [comment]
I went through and cleared all 'gene symbol to date' issues and did not find any symbols in the interaction file or gene input for the M5 module, but still no luck. Is it possible there are too few of genes to generate a interaction plot? I may look to employ a different interaction table, which would likely yield similar results?

**Comment by pedrostrusso** [comment]
Would you mind sending me your data and exactly how you're running it so I could take a look? pedrostrusso at gmail dot com

**Comment by NickFiore-1** [comment]
Sent!

**Comment by pedrostrusso** [comment]
Hi @NickFiore-1 I found what's wrong: it seems none of the M5 genes are in your interactions file. You can confirm this with the following:
`m5 <- module_genes(cem, "M5")[, 1]`
`any(m5 %in% int_df$gene1symbol)`
`any(m5 %in% int_df$gene2symbol)`

**Comment by NickFiore-1** [comment]
Thank you for finding the issue! Apologies, I should have checked this and saved your time. Much appreciated.
