### ISSUE TITLE
Difference between the results obtained with Rscript and the results obtained from the Cemitool site

### ISSUE THREAD

**Issue by mohamadysn** [csbl-usp/CEMiTool#95]
Hello,

I used your sample files given on the cemitool site, and tried if I could get the same results with the R script!

I didn't change the settings on the site just i used vst, so I ran it with the 0.1 filter.

In my R script I did the same and just set the min_ngen=20 and apply_vst = TRUE to have the same settings with the site.

I got the same number of modules and the same number of genes in each module, but when I compared the GSEA I saw the difference! 

![gsea-plot-1_Script_R](https://user-images.githubusercontent.com/97467554/196174083-06ac02e4-e2cb-4004-9808-ee3483056425.png)

To view it:
https://ibb.co/BGz6wmM

To view it:
![site_results_GSEA](https://user-images.githubusercontent.com/97467554/196174417-20b5d306-9d2f-4ea3-913b-dd7ab18e8769.png)

https://ibb.co/B373bBk

do you have an explanation for this issue?

Thank you in advance

**Comment by pedrostrusso** [comment]
Hi @mohamadysn,
I don't know if/how webCEMiTool is being maintained, so I can't answer your question. Please send an e-mail to hnakaya at usp dot com dot br for information on the webtool.
