### ISSUE TITLE
Problems formating GMT file

### ISSUE THREAD

**Issue by Mxrcon** [csbl-usp/CEMiTool#98]
Hey :wave: @pedrostrusso,

I've been using cemitools and calculated the basic modules analysis, my RNa expression table came from Trinity, and all genes are annotated with isoform ID `TRINITY_DN0_c0_g1_i1.p3`, I'm preparing a GMT file with kegg and cog annotation of each isoform. and I'm confused if the "GENE" could be any ID provided, or it should be the cog or kegg ID, or something else. the term is only the function attributed to the gene right?

Thanks for your attention!

**Comment by Mxrcon** [comment]
Hey @pedrostrusso, I'm getting the same error again:

heres my error code:
```
--> No gene can be mapped....
--> Expected input gene ID: E3.4.17.25,DPYD,RP-L10Ae,MSI,DDX5,MYBP
--> return NULL...
--> No gene can be mapped....
--> Expected input gene ID: E3.4.17.25,DDX5,DPYD,MYBP,RP-L10Ae,MSI
--> return NULL...
--> No gene can be mapped....
--> Expected input gene ID: E3.4.17.25,DPYD,MYBP,RP-L10Ae,CHS,MSI
--> return NULL...
--> No gene can be mapped....
--> Expected input gene ID: MSI,MYBP,RP-L10Ae,DDX5,CHS,DPYD
--> return NULL...
--> No gene can be mapped....
--> Expected input gene ID: DPYD,MSI,MYBP,DDX5,CHS,RP-L10Ae
--> return NULL...
Warning messages:
1: In FUN(X[[i]], ...) : Enrichment for module M1 is NULL
2: In FUN(X[[i]], ...) : Enrichment for module M2 is NULL
3: In FUN(X[[i]], ...) : Enrichment for module M3 is NULL
4: In FUN(X[[i]], ...) : Enrichment for module M4 is NULL
5: In .local(cem, ...) :
```

This is an example of my expression file: 
```
5185c0g1i16 | 63 | 103 | 35 | 143 | 403 | 97
6694c0g1i1 | 12 | 19 | 8 | 79 | 0 | 24
12725c0g2i3 | 10 | 13 | 0 | 11 | 49 | 91
2609c0g1i10 | 0 | 13 | 0 | 12 | 19 | 73
12374c0g1i4 | 52 | 40 | 17 | 65 | 16 | 37
3183c0g1i15 | 93 | 68 | 81 | 116 | 27 | 82
8516c1g2i5 | 15 | 25 | 15 | 39 | 97 | 84
16171c0g1i1 | 19 | 22 | 19 | 22 | 0 | 1
3036c0g1i11 | 128 | 60 | 120 | 226 | 10 | 90
7053c3g1i1 | 19 | 16 | 20 | 3 | 0 | 4
```

My gmt imported looks like this:
```
gene | term
2 | 0c0g1i2 | CHS
3 | 0c0g1i3 | CHS
4 | 0c11g1i1 | MSI
5 | 0c16g1i1 | DPYD
6 | 0c1g1i1 | RP-L10Ae
7 | 0c26g1i1 | DPYD
8 | 0c4g1i1 | MYBP
9 | 0c8g1i1 | DDX5
10 | 10000c1g1i10 | SPA1_2
11 | 10000c1g1i11 | SPA1_2
12 | 10000c1g1i12 | SPA1_2
13 | 10000c1g1i7 | SPA1_2
14 | 10000c2g1i1 | C1QBP
15 | 10000c4g1i2 | C1QBP
16 | 10001c2g1i2 | PINX1
17 | 10001c2g1i3 | PINX1



```

I'm running CEMiTool version 1.22.0 on Linux Mint 20.3 x86_64

**Comment by pedrostrusso** [comment]
Hi @Mxrcon it seems that fgsea (which CEMiTool runs under the hood) can't find the module genes' names in your GMT file. Are you sure *all* genes from your expression file are present (and perfectly matching) in your GMT file? Also, from the GMT example you posted it would seem that you have 3 columns in your GMT. CEMiTool will not remove that index column for you, so please try removing it yourself before feeding it in.
